// Generated by gencpp from file servo_drive/Angle.msg
// DO NOT EDIT!


#ifndef SERVO_DRIVE_MESSAGE_ANGLE_H
#define SERVO_DRIVE_MESSAGE_ANGLE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace servo_drive
{
template <class ContainerAllocator>
struct Angle_
{
  typedef Angle_<ContainerAllocator> Type;

  Angle_()
    : angle_1(0.0)
    , angle_2(0.0)
    , angle_3(0.0)  {
    }
  Angle_(const ContainerAllocator& _alloc)
    : angle_1(0.0)
    , angle_2(0.0)
    , angle_3(0.0)  {
  (void)_alloc;
    }



   typedef float _angle_1_type;
  _angle_1_type angle_1;

   typedef float _angle_2_type;
  _angle_2_type angle_2;

   typedef float _angle_3_type;
  _angle_3_type angle_3;





  typedef boost::shared_ptr< ::servo_drive::Angle_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::servo_drive::Angle_<ContainerAllocator> const> ConstPtr;

}; // struct Angle_

typedef ::servo_drive::Angle_<std::allocator<void> > Angle;

typedef boost::shared_ptr< ::servo_drive::Angle > AnglePtr;
typedef boost::shared_ptr< ::servo_drive::Angle const> AngleConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::servo_drive::Angle_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::servo_drive::Angle_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace servo_drive

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'servo_drive': ['/home/lzw/ding/src/servo_drive/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::servo_drive::Angle_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::servo_drive::Angle_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::servo_drive::Angle_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::servo_drive::Angle_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::servo_drive::Angle_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::servo_drive::Angle_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::servo_drive::Angle_<ContainerAllocator> >
{
  static const char* value()
  {
    return "7023de6969abdb6bc7e604ee027fa612";
  }

  static const char* value(const ::servo_drive::Angle_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x7023de6969abdb6bULL;
  static const uint64_t static_value2 = 0xc7e604ee027fa612ULL;
};

template<class ContainerAllocator>
struct DataType< ::servo_drive::Angle_<ContainerAllocator> >
{
  static const char* value()
  {
    return "servo_drive/Angle";
  }

  static const char* value(const ::servo_drive::Angle_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::servo_drive::Angle_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 angle_1\n\
float32 angle_2\n\
float32 angle_3\n\
";
  }

  static const char* value(const ::servo_drive::Angle_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::servo_drive::Angle_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.angle_1);
      stream.next(m.angle_2);
      stream.next(m.angle_3);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Angle_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::servo_drive::Angle_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::servo_drive::Angle_<ContainerAllocator>& v)
  {
    s << indent << "angle_1: ";
    Printer<float>::stream(s, indent + "  ", v.angle_1);
    s << indent << "angle_2: ";
    Printer<float>::stream(s, indent + "  ", v.angle_2);
    s << indent << "angle_3: ";
    Printer<float>::stream(s, indent + "  ", v.angle_3);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SERVO_DRIVE_MESSAGE_ANGLE_H
